In [40]:
path = 'C:/Users/Hcedu/Documents/Kai/Python/0624/students_table.txt'

with open(path) as f:
    # print(repr(f.readline()))
    data_list_2D = []
    n = 0
    while True:
        str1 = f.readline()
        t = str1.split()
        if t ==[]:
            break
        else:
            t[2] = int(t[2])
            t[3] = int(t[3])
            t.append((t[2]+t[3])/2)
            data_list_2D.append(t)
            n+1
    print(data_list_2D)

[['林治宏', '01', 57, 57, '2001/12/10', 57.0], ['陳建偉', '02', 68, 77, '2005/06/27', 72.5], ['鍾祖培', '03', 89, 52, '2001/08/19', 70.5], ['鄭榮仁', '04', 68, 56, '2003/10/22', 62.0], ['廖天珩', '05', 53, 51, '2002/05/21', 52.0], ['宋立群', '06', 99, 85, '2005/01/12', 92.0], ['呂文凱', '07', 97, 97, '1996/04/03', 97.0], ['吳采曄', '08', 89, 94, '2005/01/28', 91.5], ['方品絨', '09', 94, 94, '2002/09/28', 94.0], ['李界寬', '10', 93, 67, '2002/09/19', 80.0], ['古智誠', '11', 63, 51, '2003/06/15', 57.0], ['吳辰桀', '12', 68, 98, '1997/09/15', 83.0], ['楊尚謙', '13', 98, 53, '1999/04/20', 75.5], ['范佐謙', '14', 80, 71, '2002/04/27', 75.5], ['沈柏臻', '15', 67, 86, '2000/08/12', 76.5], ['陳恩生', '16', 71, 61, '2002/04/26', 66.0], ['徐豪岑', '17', 67, 74, '1997/07/08', 70.5], ['王彥傑', '18', 89, 78, '2002/02/09', 83.5], ['彭瑋翊', '19', 93, 60, '2004/01/12', 76.5], ['周哲民', '20', 62, 51, '1999/12/28', 56.5], ['陳邑溓', '21', 50, 83, '1998/12/12', 66.5], ['姜冠宏', '22', 82, 89, '2000/04/19', 85.5], ['彭明偉', '23', 75, 58, '2005/11/05', 66.5], ['詹昇諭', '24', 89, 75, '2002/06/17', 82.0], ['陳家慶', '25', 58, 61, '2005/09/14', 59.5], ['劉凡綺', '26', 70, 60, '1997/09/11', 65.0], ['黃連豐', '27', 70, 70, '2002/12/14', 70.0], ['古文晴', '28', 97, 99, '2003/07/06', 98.0], ['王文鴻', '29', 99, 56, '2000/10/13', 77.5], ['古家宇', '30', 83, 69, '1996/08/03', 76.0]]

In [ ]:
a=24
b=7
(a%b*100)//2.0**3.0-b

In [ ]:
a = -5 < 0 <5
a

In [ ]:
a = '567'
b = a*5
b

In [ ]:
def reverse_pname(backwards_pname):
    forward_pname = ''
    for index in range(len(backwards_pname)-1,-1,-1) :
        forward_pname += backwards_pname[index]
    return forward_pname

print(reverse_pname("klim")) #test case

In [ ]:
alph = "abcdefghijklmnopqrstuvwxyz"
a = alph[3:15]
b = alph[3:15:3]
c = alph[15:3:-3]
d = alph[::-3]
d

In [ ]:
def ticket_fee(age, school):
    fee = 0
    if age >= 5 and school == True :
        fee = 60
    if age >= 5 and school == False :
        if age <= 17 :
            fee = 120
        else :
            fee = 180
    return fee

ticket_fee(35, True)

![The San Juan Mountains are beautiful!](./Users/Hcedu/Documents/Kai/Python/Listcomprehensions.jpg "串列生成式小抄")

![Listcomprehensions!](./Listcomprehensions.jpg)

![Listcomprehensions!](./san-juan-mountains "串列生成式小抄")

[![An old rock in the desert](/assets/images/shiprock.jpg "Shiprock, New Mexico by Beau Rogers")](https://www.flickr.com/photos/beaurogers/31833779864/in/photolist-Qv3rFw-34mt9F-a9Cmfy-5Ha3Zi-9msKdv-o3hgjr-hWpUte-4WMsJ1-KUQ8N-deshUb-vssBD-6CQci6-8AFCiD-zsJWT-nNfsgB-dPDwZJ-bn9JGn-5HtSXY-6CUhAL-a4UTXB-ugPum-KUPSo-fBLNm-6CUmpy-4WMsc9-8a7D3T-83KJev-6CQ2bK-nNusHJ-a78rQH-nw3NvT-7aq2qf-8wwBso-3nNceh-ugSKP-4mh4kh-bbeeqH-a7biME-q3PtTf-brFpgb-cg38zw-bXMZc-nJPELD-f58Lmo-bXMYG-bz8AAi-bxNtNT-bXMYi-bXMY6-bXMYv)

2024-06-27

In [ ]:
squares = []
for x in range(10):
    squares.append(x**2)
squares

In [ ]:
squares = list(map(lambda x: x**2, range(10)))

# squares = [x**2 for x in range(10)]

In [ ]:
list (map(str.lower,['ABCD', 'Abc', 'ab']))

In [ ]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x!= y]

In [ ]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

combs

In [ ]:
vec = [-4, -2, 0, 2, 4]
# create a new list with the values doubled
[x*2 for x in vec]

# filter the list to exclude negative numbers
[x for x in vec if x >= 0]

# apply a function to all the elements
[abs(x) for x in vec]

# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

# the tuple must be parenthesized, otherwise an error is raised
# [x, x**2 for x in range(6)]
#   File "<stdin>", line 1
#     [x, x**2 for x in range(6)]
#      ^^^^^^^
SyntaxError: did you forget parentheses around the comprehension target?
# flatten a list using a listcomp with two 'for'
# 2D to 1D
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

In [ ]:
from math import pi
[str(round(pi, i)) for i in range(1, 6)]

In [ ]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

In [ ]:
[[row[i] for row in matrix] for i in range(4)]

In [ ]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

transposed

In [ ]:
transposed = []
for i in range(4):
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

transposed

In [ ]:
[(x, x**2, x**3) for x in range(6)]

In [ ]:
[n for n in range(5,0,-1)]

In [ ]:
[n for n in range(1,6)]

In [ ]:
import math

[int(math.fabs(4-math.fabs(n)+1)+1) for n in range(9,0,-1)]

In [ ]:
import math

# [n for n in range(1,11)]
# [n for n in range(1,11)][n for n in range(1,11)]
[n for n in range(1,11)]

In [ ]:
#A
# product_no = ""
#B
product_no = "sentinel"
parts = ""

#A
while product_no != "":
#B
# while product_no != "sentinel":

    #A
    #valid = False
    #B
    #valid = True
    product_no = input("Enter product number (dd-dddd): ")
    parts = product_no.split('-')
    if len(parts) == 2:
        if len(parts[0]) == 2 and len(parts[1]) == 4:
            if parts[0].isdigit() and parts[1].isdigit():
        
        #A
        # valid = False
        #B
                valid = True
        print(valid)

# 2024-07-01 證照考試解題  格式化字串  例外處理

string — Common string operations

https://docs.python.org/3/library/string.html

In [ ]:
import Kai

path = 'C:/Users/Hcedu/Documents/Kai/Python/0624/students_table1.txt'

with open(path,mode='r') as f:
    data = f.read()

data_list = data.split()

print('id ',' s1 ',' s2 ','  avg ','age ','rank ', 'name')
print('== ','=== ','=== ','===== ','=== ','==== ','======')

data_list_2D = []
n = 0
while True :

    t = data_list[0 + n * 5: 5 + n * 5]

    if t == [] :
        break
    else :
        t[2] = int(t[2])
        t[3] = int(t[3])
        t.append( (t[2]+t[3])/2 )
        data_list_2D.append(t)
        n += 1

data_list_2D_0 = sorted( data_list_2D, key = lambda x : x[5], reverse=True)

目前名次 = 1
上一位同學的成績 = data_list_2D_0[0][5]

for n,item in enumerate(data_list_2D_0,1) :
    if n == 1 or item[5] == 上一位同學的成績:
        print('%s  %3d  %3d  %5.1f   %s   %2d    %-3s' %
            (item[1],item[2],item[3],item[5],Kai.find_age(item[4]),目前名次,item[0]))
    else :
        print('%s  %3d  %3d  %5.1f   %s   %2d    %-3s' %
              (item[1],item[2],item[3],item[5],Kai.find_age(item[4]),n,item[0]))
        目前名次 = n
    上一位同學的成績 = item[5]

In [ ]:
"The sum of 1 + 2 is {0}".format(1+2)

In [ ]:
import Kai

path = 'C:/Users/Hcedu/Documents/Kai/Python/0624/students_table1.txt'

with open(path,mode='r') as f:
    data = f.read()

data_list = data.split()

print('id ',' s1 ',' s2 ','  avg ','age ','rank ', 'name')
print('== ','=== ','=== ','===== ','=== ','==== ','======')

data_list_2D = []
n = 0
while True :

    t = data_list[0 + n * 5: 5 + n * 5]

    if t == [] :
        break
    else :
        t[2] = int(t[2])
        t[3] = int(t[3])
        t.append( (t[2]+t[3])/2 )
        data_list_2D.append(t)
        n += 1

data_list_2D_0 = sorted( data_list_2D, key = lambda x : x[5], reverse=True)

目前名次 = 1
上一位同學的成績 = data_list_2D_0[0][5]

for n,item in enumerate(data_list_2D_0,1) :
    if n == 1 or item[5] == 上一位同學的成績:
        print('{1:2s}{2:3d}{3:3d}{5:5.1f}{4:3d}{6:4d}{0:3s}'.format(item[0],item[1],item[2],item[3],Kai.find_age(item[4]),item[5],目前名次))
        # print( '{1:2s}  {2:3d}  {3:3d}  {5:5.1f}  {4:3d}  {6:4d}  {0:3s}'.format(item[0],item[1],item[2],item[3],采曄.算年齡(item[4]),item[5],目前名次)
    else :
        print('%s  %3d  %3d  %5.1f   %s   %2d    %-3s' %
              (item[1],item[2],item[3],item[5],Kai.find_age(item[4]),n,item[0]))
        目前名次 = n
    上一位同學的成績 = item[5]

In [ ]:
import Kai

path = 'C:/Users/Hcedu/Documents/Kai/Python/0624/students_table1.txt'

with open(path,mode='r') as f:
    data = f.read()

data_list = data.split()

print('id ',' s1 ',' s2 ','  avg ','age ','rank ', 'name')
print('== ','=== ','=== ','===== ','=== ','==== ','======')

data_list_2D = []
n = 0
while True :

    t = data_list[0 + n * 5: 5 + n * 5]

    if t == [] :
        break
    else :
        t[2] = int(t[2])
        t[3] = int(t[3])
        t.append( (t[2]+t[3])/2 )
        data_list_2D.append(t)
        n += 1

data_list_2D_0 = sorted( data_list_2D, key = lambda x : x[5], reverse=True)

目前名次 = 1
上一位同學的成績 = data_list_2D_0[0][5]

for n,item in enumerate(data_list_2D_0,1) :
    if n == 1 or item[5] == 上一位同學的成績:
        print(f'{item[1]:2s} {item[2]:3d} {item[3]:3d} {item[5]:5.1f} {Kai.find_age(item[4]):3d} {目前名次:4d} {item[0]:3s}' )
        # print( f'{item[1]:2s}  {item[2]:3d}  {item[3]:3d}  {item[5]:5.1f}  {Kai.find_age(item[4]):3d}  {目前名次:4d}  {item[0]:3s}' )
    else :
        print('%s  %3d  %3d  %5.1f   %s   %2d    %-3s' %
              (item[1],item[2],item[3],item[5],Kai.find_age(item[4]),n,item[0]))
        目前名次 = n
    上一位同學的成績 = item[5]

https://docs.python.org/3/library/string.html

In [ ]:
"{0:09_.1f}".format(123456.678)

# How to write nested loops in Python

https://note.nkmk.me/en/python-break-nested-loops/

# 4. More Control Flow Tools

https://docs.python.org/3/tutorial/controlflow.html

In [ ]:
for n in range(2, 100):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        # loop fell through without finding a factor
        print(n, 'is a prime number')

# Exception hierarchy

https://docs.python.org/3/library/exceptions.html#exception-hierarchy

# 2024-07-02

https://steam.oxxostudio.tw/category/python/basic/try-except.html

In [ ]:
try:
    a = int(input('輸入 0～9：'))
    if a>9:       # 如果輸入的 a 大於 9
        raise       # 強制中斷，拋出錯誤資訊席
    print(a)
except :
    print('有錯誤喔～')   # 收到錯誤訊息，顯示錯誤

In [5]:
try:
    a = int(input('輸入 0～9：'))
    if a>9:
        raise ValueError('數字不在範圍內')
    print(a)
except ValueError as msg:    # 如果輸入範圍外的數字或解析非 10 進位數字，執行這邊的程式
    print(msg)
except :                     # 其他錯誤，執行這邊的程式
    print('有錯誤喔～')
print('繼續執行')

輸入 0～9： 10

數字不在範圍內
繼續執行

In [6]:
try:
    a = int(input('輸入 0～9：'))
    if a>9:
        assert False, '數字不在範圍內'
    print(a)
except AssertionError as msg:
    print(msg)
except :
    print('有錯誤喔～')
print('繼續執行')

輸入 0～9： 10

數字不在範圍內
繼續執行

In [6]:
a = dict(name='oxxo', age=18, eat=['apple','banana'])
print(a)          # {'name': 'oxxo', 'age': 18, 'eat': ['apple', 'banana']}
print(type(a));   # <class 'dict'>
print(a['eat'][1])

{'name': 'oxxo', 'age': 18, 'eat': ['apple', 'banana']}
<class 'dict'>
banana

# 2024-07-08 Pandas

In [25]:
import numpy as np
import pandas as pd

In [28]:
import dlib
import talib

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [23]:
s1 = pd.Series()

In [ ]:
print(dir(s1))

In [8]:
df1 = pd.DataFrame()

In [9]:
type(df1)

pandas.core.frame.DataFrame

In [12]:
s = pd.Series()

In [13]:
s = s.append(pd.Series([1]))

AttributeError: 'Series' object has no attribute 'append'

In [16]:
s['Kai'] = 100

In [18]:
s['abc'] = 90

In [19]:
s['ABC'] = 80

In [20]:
s

Kai    100
abc     90
ABC     80
dtype: int64

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame

In [31]:
df1 = df1.append({'name':'Kai','comu1':100,'comu2':90})

AttributeError: 'DataFrame' object has no attribute 'append'

In [36]:
df1 = pd.DataFrame({'name':['Kai','abc'],'comu1':[100,98],'comu2':[90,78]})

In [37]:
df1

  name  comu1  comu2
0  Kai    100     90
1  abc     98     78

In [41]:
df2 = pd.DataFrame()

In [ ]:
df2 = pd.contcatt([df2,df1])

In [44]:
print(data_list_2D)

[['林治宏', '01', 57, 57, '2001/12/10', 57.0], ['陳建偉', '02', 68, 77, '2005/06/27', 72.5], ['鍾祖培', '03', 89, 52, '2001/08/19', 70.5], ['鄭榮仁', '04', 68, 56, '2003/10/22', 62.0], ['廖天珩', '05', 53, 51, '2002/05/21', 52.0], ['宋立群', '06', 99, 85, '2005/01/12', 92.0], ['呂文凱', '07', 97, 97, '1996/04/03', 97.0], ['吳采曄', '08', 89, 94, '2005/01/28', 91.5], ['方品絨', '09', 94, 94, '2002/09/28', 94.0], ['李界寬', '10', 93, 67, '2002/09/19', 80.0], ['古智誠', '11', 63, 51, '2003/06/15', 57.0], ['吳辰桀', '12', 68, 98, '1997/09/15', 83.0], ['楊尚謙', '13', 98, 53, '1999/04/20', 75.5], ['范佐謙', '14', 80, 71, '2002/04/27', 75.5], ['沈柏臻', '15', 67, 86, '2000/08/12', 76.5], ['陳恩生', '16', 71, 61, '2002/04/26', 66.0], ['徐豪岑', '17', 67, 74, '1997/07/08', 70.5], ['王彥傑', '18', 89, 78, '2002/02/09', 83.5], ['彭瑋翊', '19', 93, 60, '2004/01/12', 76.5], ['周哲民', '20', 62, 51, '1999/12/28', 56.5], ['陳邑溓', '21', 50, 83, '1998/12/12', 66.5], ['姜冠宏', '22', 82, 89, '2000/04/19', 85.5], ['彭明偉', '23', 75, 58, '2005/11/05', 66.5], ['詹昇諭', '24', 89, 75, '2002/06/17', 82.0], ['陳家慶', '25', 58, 61, '2005/09/14', 59.5], ['劉凡綺', '26', 70, 60, '1997/09/11', 65.0], ['黃連豐', '27', 70, 70, '2002/12/14', 70.0], ['古文晴', '28', 97, 99, '2003/07/06', 98.0], ['王文鴻', '29', 99, 56, '2000/10/13', 77.5], ['古家宇', '30', 83, 69, '1996/08/03', 76.0]]

In [45]:
dict1=dict(data_list_2D)
print(dict1)

ValueError: dictionary update sequence element #0 has length 6; 2 is required

In [46]:
index = [n for n in range(1,31)]

In [52]:
column = ['name','id','comu1','comu2','birthday','average']

In [49]:
column

['name', 'id', 'comu1', 'comu2', 'birdary', 'average']

In [53]:
df2 = pd.DataFrame(data_list_2D,index,column)

In [55]:
df2['avg']=(df2.loc[:,'comu1']+df2.loc[:,'comu2'])/2

In [60]:
df2['rank'] = df2['avg'].rank(ascending=False,method='min').astype(np.uint8)

In [61]:
df2

   name  id  comu1  comu2    birthday  average   avg  rank
1   林治宏  01     57     57  2001/12/10     57.0  57.0    27
2   陳建偉  02     68     77  2005/06/27     72.5  72.5    17
3   鍾祖培  03     89     52  2001/08/19     70.5  70.5    18
4   鄭榮仁  04     68     56  2003/10/22     62.0  62.0    25
5   廖天珩  05     53     51  2002/05/21     52.0  52.0    30
6   宋立群  06     99     85  2005/01/12     92.0  92.0     4
7   呂文凱  07     97     97  1996/04/03     97.0  97.0     2
8   吳采曄  08     89     94  2005/01/28     91.5  91.5     5
9   方品絨  09     94     94  2002/09/28     94.0  94.0     3
10  李界寬  10     93     67  2002/09/19     80.0  80.0    10
11  古智誠  11     63     51  2003/06/15     57.0  57.0    27
12  吳辰桀  12     68     98  1997/09/15     83.0  83.0     8
13  楊尚謙  13     98     53  1999/04/20     75.5  75.5    15
14  范佐謙  14     80     71  2002/04/27     75.5  75.5    15
15  沈柏臻  15     67     86  2000/08/12     76.5  76.5    12
16  陳恩生  16     71     61  2002/04/26     66.0  66.0    23
17  徐豪岑  17     67     74  1997/07/08     70.5  70.5    18
18  王彥傑  18     89     78  2002/02/09     83.5  83.5     7
19  彭瑋翊  19     93     60  2004/01/12     76.5  76.5    12
20  周哲民  20     62     51  1999/12/28     56.5  56.5    29
21  陳邑溓  21     50     83  1998/12/12     66.5  66.5    21
22  姜冠宏  22     82     89  2000/04/19     85.5  85.5     6
23  彭明偉  23     75     58  2005/11/05     66.5  66.5    21
24  詹昇諭  24     89     75  2002/06/17     82.0  82.0     9
25  陳家慶  25     58     61  2005/09/14     59.5  59.5    26
26  劉凡綺  26     70     60  1997/09/11     65.0  65.0    24
27  黃連豐  27     70     70  2002/12/14     70.0  70.0    20
28  古文晴  28     97     99  2003/07/06     98.0  98.0     1
29  王文鴻  29     99     56  2000/10/13     77.5  77.5    11
30  古家宇  30     83     69  1996/08/03     76.0  76.0    14

In [62]:
# Kai.py
import datetime
def find_age(str_d):
    '''
    str_d ==> 輸入一個 日期 yyyy/mm/dd ex:2024/06/24\n
    return ==> 回傳年齡整數
    '''

    d = datetime.datetime.now().strftime(format='%Y/%m/%d')
    year = int(d[:4])
    month = int(d[5:7])
    day = int(d[8:])

    _year = int(str_d[:4])
    _month = int(str_d[5:7])
    _day = int(str_d[8:])

    if month > month or month == _month and day > _day:
        age = year - _year
    else:
        age = year - _year - 1
    return age


def 算年齡(str1) :
    '''
    str1 = > '2024/06/24'\n
    return => 回傳年齡整數
    '''
    d = datetime.datetime.now().strftime(format='%Y/%m/%d')
    # print(type(d))
    # print(d)
    year = int(d[:4])
    month = int(d[5:7])
    day = int(d[8:])

    _year = int(str1[:4])
    _month = int(str1[5:7])
    _day = int(str1[8:])

    if month > _month or month == _month and day > _day :
         age = year - _year
    else :
         age = year - _year - 1

    return age

In [63]:
df2['age'] = 0

In [67]:
for n,item in enumerate(df2['birthday'],0) :
    df2['age'][n] = find_age(item)

C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['age'][n] = find_age(item)
C:\Users\Hcedu\AppData\Local\Temp\ipykernel_10584\1060123836.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

In [68]:
df2

   name  id  comu1  comu2    birthday  average   avg  rank  age
1   林治宏  01     57     57  2001/12/10     57.0  57.0    27   18
2   陳建偉  02     68     77  2005/06/27     72.5  72.5    17   22
3   鍾祖培  03     89     52  2001/08/19     70.5  70.5    18   20
4   鄭榮仁  04     68     56  2003/10/22     62.0  62.0    25   21
5   廖天珩  05     53     51  2002/05/21     52.0  52.0    30   18
6   宋立群  06     99     85  2005/01/12     92.0  92.0     4   27
7   呂文凱  07     97     97  1996/04/03     97.0  97.0     2   18
8   吳采曄  08     89     94  2005/01/28     91.5  91.5     5   21
9   方品絨  09     94     94  2002/09/28     94.0  94.0     3   21
10  李界寬  10     93     67  2002/09/19     80.0  80.0    10   20
11  古智誠  11     63     51  2003/06/15     57.0  57.0    27   26
12  吳辰桀  12     68     98  1997/09/15     83.0  83.0     8   24
13  楊尚謙  13     98     53  1999/04/20     75.5  75.5    15   21
14  范佐謙  14     80     71  2002/04/27     75.5  75.5    15   23
15  沈柏臻  15     67     86  2000/08/12     76.5  76.5    12   21
16  陳恩生  16     71     61  2002/04/26     66.0  66.0    23   26
17  徐豪岑  17     67     74  1997/07/08     70.5  70.5    18   21
18  王彥傑  18     89     78  2002/02/09     83.5  83.5     7   19
19  彭瑋翊  19     93     60  2004/01/12     76.5  76.5    12   24
20  周哲民  20     62     51  1999/12/28     56.5  56.5    29   25
21  陳邑溓  21     50     83  1998/12/12     66.5  66.5    21   23
22  姜冠宏  22     82     89  2000/04/19     85.5  85.5     6   18
23  彭明偉  23     75     58  2005/11/05     66.5  66.5    21   21
24  詹昇諭  24     89     75  2002/06/17     82.0  82.0     9   18
25  陳家慶  25     58     61  2005/09/14     59.5  59.5    26   26
26  劉凡綺  26     70     60  1997/09/11     65.0  65.0    24   21
27  黃連豐  27     70     70  2002/12/14     70.0  70.0    20   21
28  古文晴  28     97     99  2003/07/06     98.0  98.0     1   23
29  王文鴻  29     99     56  2000/10/13     77.5  77.5    11   27
30  古家宇  30     83     69  1996/08/03     76.0  76.0    14    0

In [57]:
df = pd.DataFrame(data={'Animal': ['cat', 'penguin', 'dog',
                                   'spider', 'snake'],
                        'Number_legs': [4, 2, 4, 8, np.nan]})

In [58]:
df

    Animal  Number_legs
0      cat          4.0
1  penguin          2.0
2      dog          4.0
3   spider          8.0
4    snake          NaN

In [59]:
s = pd.Series(range(5), index=list("abcde"))
s["d"] = s["b"]
s.rank()

a    1.0
b    2.5
c    4.0
d    2.5
e    5.0
dtype: float64